### ISSUE TITLE
Scroll/wrap functionality

### ISSUE THREAD

**Issue by kuba-gaj** [H3rmt/hyprswitch#28]
I have an ultrawide monitor with quite a lot of workspaces and noticed they don't fit on the screen for me.
The GUI also doesn't look as nice as on the screenshots. Maybe wrapping of workspaces could be an answer

![image](https://github.com/H3rmt/hyprswitch/assets/3915056/6f63b3cb-9bc3-4656-9cab-a389526a815c)

**Comment by H3rmt** [comment]
The white background is caused by the white theme used by GTK4 (without libadwaita). You can change it using gnome-tweaks by setting the legacy-applications theme to, for example, Adwaita-dark. If you prefer to use libadwaita, you can install the program with cargo and enable the libadwaita feature.
